steps:
  - name: 'node:22-alpine'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'node:22-alpine'
    entrypoint: 'yarn'
    args: ['select:$_BRAND']
  - name: 'node:22-alpine'
    entrypoint: 'yarn'
    args: ['build']
    env: ['REACT_APP_API_URL=$_API_URL', 'REACT_APP_ENV=$_REACT_APP_ENV']
  - name: 'eu.gcr.io/brunoni-allmarine/firebase-tools'
    args: ['use', '$_BRAND', '--debug']
  - name: 'eu.gcr.io/brunoni-allmarine/firebase-tools'
    args: ['deploy', '--only', 'hosting:$BRANCH_NAME', '--debug']
timeout: '1200s'
