steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['select:$_BRAND']
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']
  - name: 'eu.gcr.io/brunoni-allmarine/firebase-tools'
    args: ['deploy', '--only', 'hosting:$_BRAND-$BRANCH_NAME']
