const quoteDetailFilterList: string[] = [
  'Bunker Adjustment Sur.',
  'Seefracht',
  'Seafreight',
  'Bunker Adjust. Factor',
  'New Bunker Factor',
  'Environmental Fuel Fee',
  'Environm. Compliance Ch.',
  'Fuel Adjustment Factor',
  'Fuel Element Contribution',
  'Low Sulphur Surcharge',
  'Emergency Bunker Surchar',
  'Emission Control Area S.',
  'Emergency Fuel Factor',
  'Interim Fuel Charge',
  'Inter Fuel Surcharge',
  'Currency Adjust. Factor',
  'Overweight Surcharge',
  'Panama Canal Surcharge',
  'Suez Canal Surcharge',
  'Aden Gulf Surcharge',
  'Peak Season Add.',
  'Piracy Surcharge',
  'War Risk Surcharge',
  'Port Additional Charge',
  'Congestion Surcharge',
  'Cost Recovery Charge',
  'Emergency Risk Surcharge',
  'Ashdod Imbalance Surch.',
  'Carrier Security Surch.',
  'Haifa Imbalance Surcharge',
  'LOW SULPHUR ADDITIONAL',
  'Carrier Security Fee',
  'Special Equipment Charge',
  'Ship Security Charge',
];

export default quoteDetailFilterList;
